sdgreg

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -50,10 +50,11 @@ jobs:
       - name: Terraform Plan
         id: tfplan
         run: |
+          set +e # Disable exit on error for this shell script block
           terraform plan -detailed-exitcode
-          echo "TF_EXIT_CODE=$?" >> $GITHUB_ENV
-        continue-on-error: true
+          exit_code=$?
+          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
 
       - name: Apply Terraform Changes
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.TF_EXIT_CODE == '2'
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.tfplan.outputs.exit_code == '2'
         run: terraform apply -auto-approve
